select *from EMPLOYEES;

SELECT *FROM DEPARTMENTS;

select FIRST_NAME from EMPLOYEES;

select FIRST_NAME,LAST_NAME from EMPLOYEES;

select * from LOCATIONS;

select city from LOCATIONS;

select COUNTRY_NAME,REGION_ID from COUNTRIES;

select JOB_ID,JOB_TITLE from JOBS;